In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[87, 47],
       [94, 91],
       [ 1,  4],
       [82, 16],
       [58, 21],
       [79, 74],
       [32, 52],
       [ 7,  6],
       [33, 99],
       [52, 71]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.92473118, 0.45263158],
       [1.        , 0.91578947],
       [0.        , 0.        ],
       [0.87096774, 0.12631579],
       [0.61290323, 0.17894737],
       [0.83870968, 0.73684211],
       [0.33333333, 0.50526316],
       [0.06451613, 0.02105263],
       [0.34408602, 1.        ],
       [0.5483871 , 0.70526316]])

## (x - x.min) / (x.max - x.min)

In [8]:
scaler_model.fit_transform(data)

array([[0.92473118, 0.45263158],
       [1.        , 0.91578947],
       [0.        , 0.        ],
       [0.87096774, 0.12631579],
       [0.61290323, 0.17894737],
       [0.83870968, 0.73684211],
       [0.33333333, 0.50526316],
       [0.06451613, 0.02105263],
       [0.34408602, 1.        ],
       [0.5483871 , 0.70526316]])

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(data = np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [11]:
df

f1  f2  f3  label
0   59  23  26     43
1   47  82   9     86
2   23  75  56     82
3   93   3  59     76
4   34  89  15     45
5   31  61  33     25
6   53  49  50      4
7   89  12  27      7
8   49  43  57     94
9    7  41   9      5
10  64  81  72     15
11   3  65   2     57
12  66   6   5     69
13  69  28  31     17
14  35  53  80     14
15  70  31  37     86
16  21  45  84     49
17  49  19  44     21
18  24  27   0     88
19  65  48  94     69
20   8  84  43     86
21  46   4  86     25
22  29  79   4     11
23  46  75  66     74
24  90  13  95     88
25  59  80  29     88
26  18  10  99     53
27  72   1  96     56
28  38  46  87     31
29   7  35  25     33
30  29  40  33     26
31  38  99   3     33
32  65  33   1     11
33  46  75  61     59
34  60  91  13    100
35  33  67  97     50
36  73  73  64     72
37  35  15  65      6
38  93  45  29     65
39  80  35  79     21
40  49  87  75     81
41  37  32  49     14
42   5  75   0     37
43  46  35  21     44
44  10  24  64     71
45  90  97   4     37
46   1  80  64     52
47  64  83  83     27
48  38  65  56     76
49   5  25  40     37

In [12]:
X = df[['f1','f2','f3']]

In [13]:
X

f1  f2  f3
0   59  23  26
1   47  82   9
2   23  75  56
3   93   3  59
4   34  89  15
5   31  61  33
6   53  49  50
7   89  12  27
8   49  43  57
9    7  41   9
10  64  81  72
11   3  65   2
12  66   6   5
13  69  28  31
14  35  53  80
15  70  31  37
16  21  45  84
17  49  19  44
18  24  27   0
19  65  48  94
20   8  84  43
21  46   4  86
22  29  79   4
23  46  75  66
24  90  13  95
25  59  80  29
26  18  10  99
27  72   1  96
28  38  46  87
29   7  35  25
30  29  40  33
31  38  99   3
32  65  33   1
33  46  75  61
34  60  91  13
35  33  67  97
36  73  73  64
37  35  15  65
38  93  45  29
39  80  35  79
40  49  87  75
41  37  32  49
42   5  75   0
43  46  35  21
44  10  24  64
45  90  97   4
46   1  80  64
47  64  83  83
48  38  65  56
49   5  25  40

In [14]:
y= df['label']

In [15]:
y

0      43
1      86
2      82
3      76
4      45
5      25
6       4
7       7
8      94
9       5
10     15
11     57
12     69
13     17
14     14
15     86
16     49
17     21
18     88
19     69
20     86
21     25
22     11
23     74
24     88
25     88
26     53
27     56
28     31
29     33
30     26
31     33
32     11
33     59
34    100
35     50
36     72
37      6
38     65
39     21
40     81
41     14
42     37
43     44
44     71
45     37
46     52
47     27
48     76
49     37
Name: label, dtype: int32

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [18]:
X_train.shape

(35, 3)

In [19]:
X_test.shape

(15, 3)

x --> data
y --> label