In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
num_input = 2
num_neurons = 3

In [4]:
x0 = tf.placeholder(tf.float32, [None, num_input])
x1 = tf.placeholder(tf.float32, [None, num_input])

In [7]:
Wx = tf.Variable(tf.random_normal(shape= [num_input, num_neurons]))
Wy = tf.Variable(tf.random_normal(shape= [num_neurons,num_neurons]))
b = tf.Variable(tf.zeros([1,num_neurons]))

In [8]:
y0 = tf.tanh(tf.matmul(x0,Wx)+b)
y1 = tf.tanh(tf.matmul(y0,Wy)+ tf.matmul(x1,Wx) + b)

In [9]:
init = tf.global_variables_initializer()

In [10]:
x0_batch = np.array([[0,1],[2,3],[4,5]])
x1_batch = np.array([[100,101],[102,103],[104,105]])

In [11]:
with tf.Session() as sess:
    sess.run(init)
    y0_output_vals, y1_output_vals = sess.run([y0,y1], feed_dict = {x0: x0_batch, x1: x1_batch})

In [12]:
print(y0_output_vals)

[[-0.07610437  0.81518656  0.9332247 ]
 [ 0.34111533  0.9994753   1.        ]
 [ 0.65668356  0.9999986   1.        ]]


In [13]:
print(y1_output_vals)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
