In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant("hello")
mehrdad = tf.constant("mehrdad")

In [3]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [4]:
with tf.Session() as sess:
    res = sess.run(hello + mehrdad)
    

In [5]:
print(res)

b'hellomehrdad'


In [6]:
a = tf.constant(10)
b = tf.constant(20)

In [7]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [8]:
with tf.Session() as sess:
    res = sess.run(a + b)

In [9]:
res

30

In [10]:
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)

In [11]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4))
myrandu = tf.random_uniform((4,4),0,1)

In [12]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [13]:
sess = tf.InteractiveSession()

In [14]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.2447689   0.8170874  -0.49386516  0.43609038]
 [ 0.01603365 -0.01316487  0.20294231 -0.7650818 ]
 [ 0.10075294 -0.9081285   0.25999036 -0.21037717]
 [-1.3865982   0.34151486 -2.9243784  -0.85493773]]


[[0.7349398  0.9378233  0.5937054  0.45283628]
 [0.46308517 0.89070785 0.85466325 0.46375394]
 [0.852942   0.6523392  0.04591727 0.50245726]
 [0.51193035 0.04990685 0.92374384 0.7071073 ]]




In [16]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.3319789   0.26691717  0.91311836 -1.0245838 ]
 [-0.18031864 -0.5242166  -0.38687944 -0.7048034 ]
 [ 3.05331    -0.99118215 -0.21277405  1.0129756 ]
 [ 1.0221437   0.21291067  0.04669109 -0.59569454]]


[[0.37048817 0.05934203 0.7119602  0.4958111 ]
 [0.18769479 0.48975134 0.10283077 0.49243426]
 [0.32665646 0.42337513 0.927251   0.72083104]
 [0.15418386 0.09947944 0.26782763 0.47321522]]




In [17]:
a = tf.constant([[1,2],[3,4]])

In [18]:
a.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_5:0' shape=(2, 2) dtype=int32>>

In [19]:
b = tf.constant([[10],[100]])

In [20]:
b.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_6:0' shape=(2, 1) dtype=int32>>

In [21]:
res = tf.matmul(a,b)
print(res.eval())

[[210]
 [430]]
